Epoch 1/5
8090/8090 [==============================] - 21s 3ms/sample - loss: 3.1737 - acc: 0.1749 - val_loss: 7.9362 - val_acc: 0.0657
Epoch 2/5
8090/8090 [==============================] - 9s 1ms/sample - loss: 2.4121 - acc: 0.3105 - val_loss: 7.7103 - val_acc: 0.0598
Epoch 3/5
8090/8090 [==============================] - 9s 1ms/sample - loss: 2.0577 - acc: 0.3972 - val_loss: 6.6672 - val_acc: 0.0588
Epoch 4/5
8090/8090 [==============================] - 9s 1ms/sample - loss: 1.7183 - acc: 0.4826 - val_loss: 6.5687 - val_acc: 0.0603
Epoch 5/5
8090/8090 [==============================] - 9s 1ms/sample - loss: 1.3744 - acc: 0.5756 - val_loss: 4.7572 - val_acc: 0.1626
Epoch 6/10
8090/8090 [==============================] - 9s 1ms/sample - loss: 1.0151 - acc: 0.6789 - val_loss: 3.3258 - val_acc: 0.2585
Epoch 7/10
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.6864 - acc: 0.7803 - val_loss: 2.8455 - val_acc: 0.3075
Epoch 8/10
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.4530 - acc: 0.8546 - val_loss: 2.8089 - val_acc: 0.3668
Epoch 9/10
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.3037 - acc: 0.9074 - val_loss: 3.0385 - val_acc: 0.3737
Epoch 10/10
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1711 - acc: 0.9520 - val_loss: 3.2316 - val_acc: 0.3786
Epoch 11/15
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1134 - acc: 0.9714 - val_loss: 3.2858 - val_acc: 0.3757
Epoch 12/15
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1089 - acc: 0.9701 - val_loss: 3.2152 - val_acc: 0.4004
Epoch 13/15
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1080 - acc: 0.9706 - val_loss: 3.3868 - val_acc: 0.3861
Epoch 14/15
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0765 - acc: 0.9811 - val_loss: 3.4928 - val_acc: 0.3955
Epoch 15/15
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0657 - acc: 0.9831 - val_loss: 3.2869 - val_acc: 0.3979
Epoch 16/20
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0555 - acc: 0.9858 - val_loss: 3.4629 - val_acc: 0.4083
Epoch 17/20
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1162 - acc: 0.9628 - val_loss: 3.5307 - val_acc: 0.4058
Epoch 18/20
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1126 - acc: 0.9653 - val_loss: 3.7407 - val_acc: 0.3895
Epoch 19/20
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1276 - acc: 0.9632 - val_loss: 3.7788 - val_acc: 0.3935
Epoch 20/20
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1452 - acc: 0.9509 - val_loss: 3.6625 - val_acc: 0.3979
Epoch 21/25
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1065 - acc: 0.9658 - val_loss: 4.0708 - val_acc: 0.3757
Epoch 22/25
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1200 - acc: 0.9607 - val_loss: 3.7155 - val_acc: 0.3915
Epoch 23/25
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1065 - acc: 0.9701 - val_loss: 3.6544 - val_acc: 0.4108
Epoch 24/25
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0769 - acc: 0.9780 - val_loss: 3.6856 - val_acc: 0.4063
Epoch 25/25
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0575 - acc: 0.9823 - val_loss: 3.7200 - val_acc: 0.4152
Epoch 26/30
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0351 - acc: 0.9905 - val_loss: 3.7550 - val_acc: 0.4246
Epoch 27/30
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0302 - acc: 0.9917 - val_loss: 3.7552 - val_acc: 0.4241
Epoch 28/30
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0243 - acc: 0.9943 - val_loss: 3.6211 - val_acc: 0.4281
Epoch 29/30
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0188 - acc: 0.9947 - val_loss: 3.7516 - val_acc: 0.4246
Epoch 30/30
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0164 - acc: 0.9964 - val_loss: 3.7716 - val_acc: 0.4256
Epoch 31/35
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0158 - acc: 0.9959 - val_loss: 4.0359 - val_acc: 0.3950
Epoch 32/35
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0161 - acc: 0.9958 - val_loss: 3.8980 - val_acc: 0.4301
Epoch 33/35
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0149 - acc: 0.9963 - val_loss: 4.0858 - val_acc: 0.4128
Epoch 34/35
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0117 - acc: 0.9975 - val_loss: 4.1125 - val_acc: 0.4266
Epoch 35/35
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0501 - acc: 0.9842 - val_loss: 4.4752 - val_acc: 0.3940
Epoch 36/40
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0465 - acc: 0.9857 - val_loss: 4.2401 - val_acc: 0.3806
Epoch 37/40
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0712 - acc: 0.9773 - val_loss: 4.3464 - val_acc: 0.3757
Epoch 38/40
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1454 - acc: 0.9511 - val_loss: 5.2868 - val_acc: 0.3495
Epoch 39/40
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1686 - acc: 0.9445 - val_loss: 4.5046 - val_acc: 0.3777
Epoch 40/40
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.2398 - acc: 0.9236 - val_loss: 5.4389 - val_acc: 0.3613
Epoch 41/45
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1464 - acc: 0.9533 - val_loss: 4.6723 - val_acc: 0.3613
Epoch 42/45
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0895 - acc: 0.9710 - val_loss: 4.2066 - val_acc: 0.4004
Epoch 43/45
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0618 - acc: 0.9806 - val_loss: 4.3997 - val_acc: 0.3910
Epoch 44/45
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0314 - acc: 0.9909 - val_loss: 4.1179 - val_acc: 0.4261
Epoch 45/45
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0263 - acc: 0.9920 - val_loss: 4.0632 - val_acc: 0.4182
Epoch 46/50
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0171 - acc: 0.9963 - val_loss: 4.0226 - val_acc: 0.4197
Epoch 47/50
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0140 - acc: 0.9960 - val_loss: 4.1187 - val_acc: 0.4182
Epoch 48/50
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0105 - acc: 0.9975 - val_loss: 4.0773 - val_acc: 0.4167
Epoch 49/50
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0099 - acc: 0.9974 - val_loss: 4.2484 - val_acc: 0.4162
Epoch 50/50
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0108 - acc: 0.9980 - val_loss: 4.1820 - val_acc: 0.4266
Epoch 51/55
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0068 - acc: 0.9981 - val_loss: 4.4351 - val_acc: 0.4226
Epoch 52/55
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0058 - acc: 0.9985 - val_loss: 4.3507 - val_acc: 0.4241
Epoch 53/55
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0080 - acc: 0.9980 - val_loss: 4.3046 - val_acc: 0.4271
Epoch 54/55
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0062 - acc: 0.9986 - val_loss: 4.2042 - val_acc: 0.4231
Epoch 55/55
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0089 - acc: 0.9984 - val_loss: 4.3953 - val_acc: 0.4187
Epoch 56/60
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0099 - acc: 0.9974 - val_loss: 4.5367 - val_acc: 0.4256
Epoch 57/60
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0095 - acc: 0.9978 - val_loss: 4.3440 - val_acc: 0.4197
Epoch 58/60
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0083 - acc: 0.9969 - val_loss: 4.1980 - val_acc: 0.4286
Epoch 59/60
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0099 - acc: 0.9978 - val_loss: 4.1055 - val_acc: 0.4330
Epoch 60/60
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0161 - acc: 0.9958 - val_loss: 4.5872 - val_acc: 0.4073
Epoch 61/65
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0182 - acc: 0.9941 - val_loss: 4.8821 - val_acc: 0.4058
Epoch 62/65
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0355 - acc: 0.9883 - val_loss: 4.7840 - val_acc: 0.4034
Epoch 63/65
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1112 - acc: 0.9655 - val_loss: 6.0693 - val_acc: 0.3505
Epoch 64/65
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1903 - acc: 0.9386 - val_loss: 5.4098 - val_acc: 0.3584
Epoch 65/65
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1839 - acc: 0.9393 - val_loss: 5.5919 - val_acc: 0.3534
Epoch 66/70
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.1552 - acc: 0.9481 - val_loss: 4.8942 - val_acc: 0.3811
Epoch 67/70
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0941 - acc: 0.9713 - val_loss: 4.6133 - val_acc: 0.4048
Epoch 68/70
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0684 - acc: 0.9782 - val_loss: 4.7243 - val_acc: 0.4063
Epoch 69/70
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0524 - acc: 0.9821 - val_loss: 4.7828 - val_acc: 0.4078
Epoch 70/70
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0325 - acc: 0.9901 - val_loss: 4.6139 - val_acc: 0.4142
Epoch 71/75
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0350 - acc: 0.9900 - val_loss: 4.3800 - val_acc: 0.4167
Epoch 72/75
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0217 - acc: 0.9937 - val_loss: 4.6704 - val_acc: 0.4207
Epoch 73/75
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0140 - acc: 0.9951 - val_loss: 4.4165 - val_acc: 0.4113
Epoch 74/75
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0131 - acc: 0.9963 - val_loss: 4.6095 - val_acc: 0.4246
Epoch 75/75
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0131 - acc: 0.9957 - val_loss: 4.5578 - val_acc: 0.4113
Epoch 76/80
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0113 - acc: 0.9964 - val_loss: 4.5990 - val_acc: 0.4212
Epoch 77/80
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0086 - acc: 0.9979 - val_loss: 4.7832 - val_acc: 0.4241
Epoch 78/80
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0096 - acc: 0.9975 - val_loss: 5.2351 - val_acc: 0.3979
Epoch 79/80
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0218 - acc: 0.9942 - val_loss: 4.9641 - val_acc: 0.4108
Epoch 80/80
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0177 - acc: 0.9946 - val_loss: 4.7403 - val_acc: 0.4256
Epoch 81/85
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0435 - acc: 0.9850 - val_loss: 5.1133 - val_acc: 0.3717
Epoch 82/85
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0519 - acc: 0.9836 - val_loss: 4.9313 - val_acc: 0.3964
Epoch 83/85
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0651 - acc: 0.9802 - val_loss: 5.3489 - val_acc: 0.3994
Epoch 84/85
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0462 - acc: 0.9859 - val_loss: 5.2136 - val_acc: 0.4167
Epoch 85/85
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0391 - acc: 0.9886 - val_loss: 5.1452 - val_acc: 0.4132
Epoch 86/90
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0448 - acc: 0.9868 - val_loss: 5.3737 - val_acc: 0.3895
Epoch 87/90
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0351 - acc: 0.9883 - val_loss: 5.3993 - val_acc: 0.3910
Epoch 88/90
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0434 - acc: 0.9879 - val_loss: 5.2648 - val_acc: 0.4039
Epoch 89/90
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0293 - acc: 0.9905 - val_loss: 4.6909 - val_acc: 0.4157
Epoch 90/90
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0181 - acc: 0.9942 - val_loss: 5.0402 - val_acc: 0.4009
Epoch 91/95
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0161 - acc: 0.9952 - val_loss: 4.9001 - val_acc: 0.4226
Epoch 92/95
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0160 - acc: 0.9952 - val_loss: 4.9697 - val_acc: 0.4236
Epoch 93/95
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0111 - acc: 0.9963 - val_loss: 5.0066 - val_acc: 0.4217
Epoch 94/95
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0196 - acc: 0.9949 - val_loss: 5.4557 - val_acc: 0.3940
Epoch 95/95
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0169 - acc: 0.9939 - val_loss: 5.3929 - val_acc: 0.4118
Epoch 96/100
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0170 - acc: 0.9947 - val_loss: 5.6025 - val_acc: 0.4083
Epoch 97/100
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0280 - acc: 0.9907 - val_loss: 5.2652 - val_acc: 0.4083
Epoch 98/100
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0293 - acc: 0.9907 - val_loss: 5.1704 - val_acc: 0.4024
Epoch 99/100
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0253 - acc: 0.9926 - val_loss: 5.1743 - val_acc: 0.4123
Epoch 100/100
8090/8090 [==============================] - 9s 1ms/sample - loss: 0.0325 - acc: 0.9897 - val_loss: 5.4285 - val_acc: 0.4024